### ISSUE TITLE
The app doesn't add stickers to whatsapp

### ISSUE THREAD

**Issue by xpcoder123** [viztushar/stickers-internet#1]
I run your app code and when I add a pack to whatsapp it doesn't show up there.

Can you please inspect for the reason?

Keep up great job 👍

**Comment by viztushar** [comment]
@xpcoder123 you change anything in the code??

**Comment by some28** [comment]
It works fine to me.
Thank you Tushar for sharing the code.

**Comment by some28** [comment]
@viztushar I'm wondering why we need permissions for writing and reading from external storage when we are actually writing images to internal storage in SaveImage().
https://developer.android.com/training/data-storage/files

**Comment by viztushar** [comment]
@some28 because after downloading files are stored in app folder so it need permission to write that in storage.

**Comment by xpcoder123** [comment]
@viztushar My bad the app works fine now. The only issue with whatsapp stickers on Android is that the get deleted upon uninstalling the app. Any solution for that?

**Comment by some28** [comment]
@viztushar Thanks for the reply.
Even after denying the permission for reading and writing to storage, but still the app works fine.
I'm wondering why we still need the permissions.

**Comment by viztushar** [comment]
@xpcoder123 there no solution for that because Whatsapp read the data that is store in the app and then show it in the Whatsapp so if the app is uninstall then Whatsapp can't read that data.

**Comment by viztushar** [comment]
@some28 yah you are right we don't need the permission. I'm not going to remove that right now because if someone change the storage location then it need the permission.
