### ISSUE TITLE
  public AssetFileDescriptor openAssetFile(@NonNull Uri uri, @NonNull String mode) throws FileNotFoundException //My this method is not called so tell me where is the issue bcoz i not even get any error

### ISSUE THREAD

**Issue by BijalDesaiP** [viztushar/stickers-internet#14]
Hey,   public AssetFileDescriptor openAssetFile(@NonNull Uri uri, @NonNull String mode) throws FileNotFoundException this method is not called in my sticker content provider class. and i also not found any error so tell me where is the issue in my code so this method is not called??? and i also not get the last query. I only get 2content://com.viztushar.stickers.provider.StickerContentProvider/metadata/1, and 3content://com.viztushar.stickers.provider.StickerContentProvider/stickers/1 this two queryies

**Comment by BijalDesaiP** [comment]
@viztushar plz reply me asap

**Comment by Vengat121** [comment]
do you find any solution

**Comment by BijalDesaiP** [comment]
Yes it is bcoz of stickers name r not getting through path so that asstes r
not open. So I save it with proper name

**Comment by desaibijal** [comment]
@Vengat121 Have u check in device that this image is stored with this name? and on the same location? Send me the screen shot of stored image file in device with its path Like this demo
![capture](https://user-images.githubusercontent.com/20115421/52768043-44b9f580-3052-11e9-8e2f-d26240d8eed5.PNG)

**Comment by Vengat121** [comment]
yes 
![image](https://user-images.githubusercontent.com/39154924/52780169-a3da3300-306f-11e9-837c-8b48bd0713fa.png)

**Comment by desaibijal** [comment]
@Vengat121 send me ur code @desaibijal9@gmail.com. if u dont have any problem

**Comment by Vengat121** [comment]
I have sent @desaibijal

**Comment by desaibijal** [comment]
@Vengat121 Check ur Mail

**Comment by Vengat121** [comment]
Thanks i will check it.

**Comment by desaibijal** [comment]
ok is it working @Vengat121

**Comment by Vengat121** [comment]
yes thnks :) i will my mistakes..

**Comment by desaibijal** [comment]
Have u clear abt ur mistakes? @Vengat121 
 private AssetFileDescriptor fetchFile(@NonNull Uri uri, @NonNull AssetManager am, @NonNull String fileName, @NonNull String identifier) {
        try {
            File file;
            if(fileName.endsWith(".png")){

//Here u have to check .png file and u have check webp so it will not able to get ur path

**Comment by Vengat121** [comment]
thnks :)

**Comment by desaibijal** [comment]
ur wlcm

**Comment by viztushar** [comment]
@BijalDesaiP @Vengat121 @desaibijal sorry for not replying but now im working on it and make it more stable with flutter. if you want to test the app then send me mail ill send apk

**Comment by desaibijal** [comment]
Its ok ty so much for replying. But my work on that app is completed. And I
had solve that problem.
