### ISSUE TITLE
about local and the server

### ISSUE THREAD

**Issue by Girlsmile** [viztushar/stickers-internet#2]
thanks for you code,I want to have different contentproviders, what should I do, for both the local and the server

**Comment by some28** [comment]
@Girlsmile You can define two content providers in Android manifest. One which is similar to main repo of WhatsApp Stickers and other from this repo.

**Comment by viztushar** [comment]
@Girlsmile if both use same storage folder then you don't need create second provider.

If you use my code then you have to add all local sticker into array first before the app start or after start then everything will work.
