### ISSUE TITLE
Request - Help me ✨💫

### ISSUE THREAD

**Issue by hazarbozkurt** [viztushar/stickers-internet#4]
First of all, thank you very much for sharing this source code.

I want to collect these two project files in a single apk file.

Your project (sticker downloader) and this project (sticker maker): https://github.com/idoideas/stickermaker-for-whatsapp

This provides the user to create both a sticker download and a sticker in a single apk file.

The user should be able to switch to sticker package downloader and sticker  maker screens with the help of nabigationdrawer or fab.

But unfortunately, I can't make single apk form two projects.
I'm getting weird bizarre mistakes.

Can you please help me make these two great projects into a single APK?

I've tried to do it many times, but I've got various actionbar and Java errors. And I know, it's very simple for you to do it. I hope you will help me.

👇👇I tried to, but I couldn't.👇👇👇
https://i.hizliresim.com/P1PpXO.png
https://i.hizliresim.com/oXr2bX.jpg

Sorry for my bad English
Best regards🤗

**Comment by viztushar** [comment]
@hazarbozkurt Right now I'm busy but I'll make that and send to you or I'll update code here

**Comment by hazarbozkurt** [comment]
> @hazarbozkurt Right now I'm busy but I'll make that and send to you or I'll update code here

Thank you very much for answering.
I'm looking forward to. I'm following.

Good day Sir

**Comment by hazarbozkurt** [comment]
![](https://i.imgur.com/cjOP9un.png)
I don't need it, but I bought it. :relaxed::relaxed::blush: <3 nice app

**Comment by viztushar** [comment]
@hazarbozkurt thanks for this😊
