### ISSUE TITLE
Query regarding saveTrayImage and saveImage

### ISSUE THREAD

**Issue by some28** [viztushar/stickers-internet#5]
Could you explain why we need file.delete() in saveTrayImage and saveImage?
Thank you!

Ref:
if (file.exists()) {
file.delete();
}

**Comment by hariiprasad** [comment]
My stickers are not loading when i placed my stickers in contents.json file    what to do now?

**Comment by hariiprasad** [comment]
@some28 Can anyone say.... What exactly the edits that needs to this source code for building a app

**Comment by some28** [comment]
@hariiprasad Have you tried running the contents.json file provided in this repo?
https://gist.github.com/viztushar/08845eb0d66572101515b22a471cd54c
It should just work fine if you use the above link.
After that create your own contents.json file with your contents.
You need to host your contents json file and images somewhere to make it work.

**Comment by hariiprasad** [comment]
@some28 Hii broo thanks for your reply
I haved tried with the given json file it worked. But when i placed my links its not working.

**Comment by viztushar** [comment]
@hariiprasad you have to change one line then it will work.

Go to **StickerAdapter**  and find **URL**  and change to your **base url**  then it will work.

**Comment by hariiprasad** [comment]
@some28 @viztushar  its worked bro thanks

**Comment by some28** [comment]
Thanks for the reply @viztushar
