### ISSUE TITLE
Download dialogue

### ISSUE THREAD

**Issue by hariiprasad** [viztushar/stickers-internet#9]
@viztushar  Hii bro, i want to add (Downloading please wait dialogue ) when downlaod button pressed. Coz when we click Downlaod button the app is running slow  or it is not allowing users to enter sticker pack. User might feel that there is a bug. 
 Can you please fix that???..

**Comment by hariiprasad** [comment]
it is also not showing Viewmore( that will redirect to playstore)  button in whatsapp when i tap sticker

**Comment by hariiprasad** [comment]
- @viztushar Bro i changed..But it still not working...

**Comment by viztushar** [comment]
@hariiprasad uninstall the app and then install app again it will work.

**Comment by hariiprasad** [comment]
@viztushar Broo i updated my app 3 times in playstore and tested within 2days and installed so many times during debugging also. Also cleared app data so many times and deleted,Added stickers to whatsapp. Still i didnt find a solution

**Comment by hariiprasad** [comment]
@viztushar bro can you please cross check this problem in your whatsapp while debugging??  You will get viewmore(in your chat screen) button when you tap on sticker if you have installed pack already.But for other users its not showing viewmore button( that will redirect to playstore).
